import { auth } from "@/lib/auth";
import { getDb } from "@/lib/db";
import { capacities } from "@/lib/schema";
import { and, desc, eq } from "drizzle-orm";
import { headers } from "next/headers";
import { NextResponse } from "next/server";

async function user(){return (await auth.api.getSession({headers:await headers()}))?.user;}
export async function GET(){const actor=await user();if(!actor)return NextResponse.json({error:"Nepřihlášený uživatel"},{status:401});return NextResponse.json(await getDb().select().from(capacities).where(eq(capacities.ownerId,actor.id)).orderBy(desc(capacities.createdAt)));}
export async function POST(request:Request){const actor=await user();if(!actor)return NextResponse.json({error:"Nepřihlášený uživatel"},{status:401});const body=await request.json();if(!body.name?.trim()||!body.role?.trim())return NextResponse.json({error:"Doplňte jméno a roli."},{status:400});const skills=String(body.skills||"").split(",").map(x=>x.trim()).filter(Boolean);const [item]=await getDb().insert(capacities).values({name:body.name.trim(),role:body.role.trim(),skills,location:body.location||null,availability:body.availability||null,ownerId:actor.id}).returning();return NextResponse.json(item,{status:201});}
export async function PATCH(request:Request){const actor=await user();if(!actor)return NextResponse.json({error:"Nepřihlášený uživatel"},{status:401});const body=await request.json();if(!body.id)return NextResponse.json({error:"Chybí ID kapacity."},{status:400});if(!body.name?.trim()||!body.role?.trim())return NextResponse.json({error:"Doplňte jméno a roli."},{status:400});const skills=String(body.skills||"").split(",").map((x:string)=>x.trim()).filter(Boolean);const [item]=await getDb().update(capacities).set({name:body.name.trim(),role:body.role.trim(),skills,location:body.location||null,availability:body.availability||null}).where(and(eq(capacities.id,body.id),eq(capacities.ownerId,actor.id))).returning();if(!item)return NextResponse.json({error:"Kapacita nebyla nalezena."},{status:404});return NextResponse.json(item);}
export async function DELETE(request:Request){const actor=await user();if(!actor)return NextResponse.json({error:"Nepřihlášený uživatel"},{status:401});const body=await request.json();if(!body.id)return NextResponse.json({error:"Chybí ID kapacity."},{status:400});const [item]=await getDb().delete(capacities).where(and(eq(capacities.id,body.id),eq(capacities.ownerId,actor.id))).returning();if(!item)return NextResponse.json({error:"Kapacita nebyla nalezena."},{status:404});return NextResponse.json({ok:true});}
